# Class 4

## Scientific Python

### Introduction

![The scientific Python stack](scientific_python.jpg)

The onion-like scientific stack of Python is composed of the most important packages used in the Python scientific world. Here's a quick overview of the most important names in the stack, before we dive in deep:
1. [IPython](https://ipython.org/): A REPL, much like the command window in MATLAB. Lets you write Python on the fly, debug and check the performance of your code, and much (much!) more.
2. [Jupyter](https://jupyter.org/): Notebooks designed for data exploration. Write code and see its output immediately, with useful rich text (Markdown) annotations to accompany it (just like this notebook!).
3. [NumPy](https://numpy.org/doc/stable/): Standard implementation of multi-dimensional arrays in Python. 
4. [pandas](https://pandas.pydata.org/docs/index.html): Tabular data manipulation.
5. [SciPy](https://www.scipy.org): Implements advanced algorithms widely used in scientific programming, including advanced linear algebra, data structures, curve fitting, signal processing, modeling and more.
6. [matplotlib](https://matplotlib.org/): A cornerstone for data visualization in Python. 
7. [seaborn](http://seaborn.pydata.org/): Smart visualizations of tabular data.

This scientific stack is one of the main reasons that empowered Python in recent years to the prominent role it has today. Throughout the course you will become familiar with all of the aforementioned tools, and more.

### NumPy

```{margin}
[This](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html) page contains a thorough comparison of similar functions in MATLAB and `numpy`. If you want to use MATLAB's `find` function and can't seem to find a counterpart in NumPy (it's `nonzero`, BTW), or if you wish to see how do different arithmetic functions compare between the two, that page can be of great assistance.
```

NumPy is the de-facto implementation of arrays in Python. They're very similar to MATLAB arrays (and to other implementations in other programming languages).

Although `numpy` is used extensively in the Python eco-system, it doesn't come with the Python standard library, which means you have to install it first. Activate your environment and run `pip install numpy` from the command line (inside VSCode, for example). Only then you can follow the rest of the class.

In [10]:
import numpy as np  # standard alias for numpy

l = [1, 2, 3]
array = np.array(l)  # obviously same as np.array([1, 2, 3])
array

array([1, 2, 3])

The created `array` variable is a `numpy` array. Notice how `numpy` has to take existing data, in this case in the form of a list (`l`), and convert it into an array. In MATLAB everything is an array all the time so we don't think of this conversion, but here the conversion happens explicitly when you call `np.array()` on some collection of data. 

Let's continue to examine the basic properties of this array:

In [7]:
# Check the dimensionality of the array:
print("Shape:\t", array.shape)
print("NDim:\t", array.ndim)

Shape:	 (3,)
NDim:	 1


We've instantiated an array by calling the `np.array()` function on an iterable. This will create a one-dimensional `numpy` array, or _vector_. This is the first important difference from MATLAB. In MATLAB, all arrays are by default _n_-dimensional. If you write:
```matlab
a = 1
a(:, :, :, :, :, 1) = 2
```
then you just received a 6-dimensional array. NumPy doesn't allow that. The dimensions of an array are generally the dimensions it had when it was created. You can always use `reshape()`, like MATLAB, to define the exact number of dimensions you wish to have. You can also use `newaxis()` to add an axis, as we'll see below. But these options still keep the number of elements in the array the same, they just re-order them.

This means that a 2x4 array can be reshaped into a 4x2 array, or a 2x2x2 one, but not 3x3x3.

The second difference is the idea of vectors.

In [8]:
print(f"The number of dimensions is {array.ndim}.")
print(f"The shape is {array.shape}.")

The number of dimensions is 1.
The shape is (3,).


As you see, `ndim` returns the number of dimensions. The `shape` is returned as a tuple, the length of which is the number of dimensions, while the values represent the number of elements in each dimensions. `shape` is very similar to the `size()` function of MATLAB.

Note that:

In [5]:
a = np.array(1)  # wrong instatiation! Don't use it, instead write np.array([1])
print("Wrong instantiation results:")
print("Shape: ", a.shape)
print("NDim: ", a.ndim)

Wrong instantiation results:
Shape:  ()
NDim:  0


So be mindful to pass an iterable.

Creating arrays with more than one dimension might look odd at a first glance:

In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(f"The number of dimensions is {arr_2d.ndim}.")
print(f"The shape is {arr_2d.shape}.")
print(f"The len of the array is {len(arr_2d)} - which corresponds to the shape of the 0th dimension.")

The number of dimensions is 2.
The shape is (2, 3).
The len of the array is 2 - which corresponds to the shape of the 0th dimension.


As we see, each list was considered a single "row" (dimension number 0) in the final array, very much like MATLAB, although the syntax can be confusing at first. Here's another slightly confusing example:

In [8]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [9]:
c.shape

(2, 2, 1)

Or, alternatively:

In [10]:
c2 = np.array([1, 2, 3, 4]).reshape((2, 2, 1))
c2.shape

(2, 2, 1)

### Getting help

NumPy has a ton of features, and to get around it we can use `lookfor` and the `?` sign, besides the official reference on the internet:

In [11]:
np.lookfor("Create array")

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a 

In [12]:
np.con*?

### Creating arrays

In [13]:
np.arange(10)  # similar to MATLAB's 0:9 (and to Python's range())

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(start=1, stop=8, step=3)  # MATLAB's 1:3:8

array([1, 4, 7])

In [15]:
np.zeros((2, 3))  # notice that the shape is a tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros_like(arr_2d)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
np.ones((1, 4), dtype='int64')  # 2-d array with the dtype argument

array([[1, 1, 1, 1]])

In [18]:
np.full((4, 2), 7)

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [19]:
np.linspace(0, 10, 3)  # start, stop, number of points (endpoint as a keyword argument)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0, 10, 3, endpoint=False, dtype=np.float32)  # float32 is "single" in MATLAB-speak. float64, which is the default, is "double"

array([0.       , 3.3333333, 6.6666665], dtype=float32)

In [21]:
np.eye(3, dtype='uint8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [22]:
np.diag([19, 20])

array([[19,  0],
       [ 0, 20]])

Some more interesting features:

In [23]:
np.array([True, False, False]) # A logical mask

array([ True, False, False])

In [24]:
np.array([1+2j]).dtype # Complex numbers

dtype('complex128')

In [11]:
np.array(['a', 'bc', 'd', 'e'])
# No such thing as a cell array, arrays can contain strings.

array(['a', 'bc', 'd', 'e'], dtype='<U2')

\* _<U2 are strings containing maximum 2 unicode letters_

Arrays can be heterogeneous, although usually this is discouraged. 
To make an hetetogeneous array, you have to specify its data type as `object`, or `np.object`:

In [26]:
np.array([1, 'b', True, {'b': 1}], dtype=object)

array([1, 'b', True, {'b': 1}], dtype=object)

The last few examples showed us that NumPy arrays are a superset of MATLAB's matrices, as they also contain the cell array functionality within them.

When multiplying NumPy arrays, multiplication is done cell-by-cell (elementwise), rather than by the rules of linear algebra. 

You can still multiply vectors and matrices using one of two options:
* The `@` operator (preferred): `arr1 @ arr2`
* `arr1.dot(arr2)`

Just remember that the default behavior is different than MATLAB's.

```{note}
NumPy does contain a matrix-like array - `np.matrix('1 2; 3 4')`, which behaves like a linear algebra 2D matrix (see [`np.matrix`](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html)), but its use is discouraged.
```

### More on datatypes

```{margin}
For more information about `dtype`s, see the [Data type objects (dtypes)](https://numpy.org/doc/stable/reference/arrays.dtypes.html) section in NumPy's official documentation.
```

While `numpy` doesn't require you to actively think of the data type of each of your arrays, it's a useful habit to have. The existing data types in `numpy` are:

In [27]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

Many array creation and handling methods have a `dtype` keyword argument, that allow you to specify the required output's data type easily.

Python will issue a `RuntimeWarning` whenever an "unsafe" conversion of data type will occur, for example from `np.float64` to `np.float32`.

### Difference between NumPy arrays and lists

You might have asked yourselves by this point what's the difference between lists and `numpy` arrays. In other words, if Python already has an array-like data structure, why does it need another one?

Lists are truly amazing, but their flexibility comes at a cost. You won't notice it when you're writing some short script, but when you start working with real datasets you notice that their performance is lacking.

Naive iteration over lists is good enough when the lists contain up to a few thousands of elements, but somewhere after this invisible threshold you will start to notice the runtimes of your app turning very slow.

#### Why are lists slower?

Lists are slower due to their implementation. Because a list has to be heterogeneous, a list is actually an object containing references to other objects, which are the elements of the data contained in the list. This nesting can go on even deeper, since elements of lists can be other lists, or other complex data types.

Iterating over such a complicated objects contains a lot of "overhead", i.e. time the interpreter tries to figure out what is it actually facing - is this current value an integer? A float? A dictionary of tuples?

![Numpy arrays versus lists](array_vs_list.png)

This is where NumPy arrays come into the picture. They require the contained data to be homogeneous (disregarding the "object" datatype), leading to a simpler structure of the underlying implementation: A NumPy array is an object with a pointer to a contiguous block of data in the memory.

NumPy forces the elements in its array to be homogeneous, by means of "upcasting":

In [28]:
arr = np.array([1, 2, 3.14, 4])
arr  # upcasted to float, not "object", since it's much slower

array([1.  , 2.  , 3.14, 4.  ])

This homogeneity and contiguity allows NumPy to use "vectorized" functions, which are simply functions that can iterate in C code over the array, as opposed to regular functions which have to use the Python iteration rules.

This means that while in essence the following two pieces of code are identical, the performance gain is due to the loop being done in C rather than in Python (this is the case in MATLAB as well):

In [29]:
%%timeit
python_array = list(range(1_000_000))
for item in python_array:
    item += 1

55.4 ms ± 665 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
%%timeit 
numpy_array = np.arange(1_000_000)
numpy_array += 1  # inside, a C loop is adding 1 to each item.

# Two orders of magnitude improvement for a pretty small (1M elements) array. 
# This is approximately the size of a 1024x1024 pixel image.

1.67 ms ± 51.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


If you recall the first class, you'll remember that we mentioned how Python code has to be transpiled into C code, which is then compiled to machine code. NumPy arrays take a "shortcut" here, are are quickly compiled to efficient C code without the Python overhead. When using vectorized NumPy operations, the loop Python does in the backstage is very similar to a loop that a C programmer would have written by hand.

Another small but significant benefit of NumPy arrays is smaller memory footprint:

In [31]:
from sys import getsizeof

python_array = list(range(1_000_000))
list_size = getsizeof(python_array) / 1e6  # in MB
print(f"Python list size (1M elements, MB): {list_size}")

numpy_array = np.arange(1_000_000, dtype=np.int32)
numpy_size = numpy_array.nbytes / 1e6
print(f"Numpy array size (1M elements, MB): {numpy_size}")

Python list size (1M elements, MB): 8.000056
Numpy array size (1M elements, MB): 4.0


```{admonition} Why do 1 million elements require 4MB?
:class: dropdown,hint    
Each element has to weigh 4 bytes, or 32 bits. This means that the `np.arange()` function generates by default `int32` values.
```

Lower memory usage can help us pack larger array in the computer's working memory (RAM), and it will also improve the performance of the underlying code.

### Indexing and slicing

Indexing `numpy` arrays is very much what you'd expect it to be.

In [32]:
a = np.arange(10)
a[0], a[3], a[-2]  # Python indexing is always done with square brackets

(0, 3, 8)

The beautiful reverse slicing works here as well:

In [33]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr_2d[0, 2]  # first row, third column

3

In [36]:
arr_2d[0, :]  # first row, all columns

array([1, 2, 3])

In [37]:
arr_2d[0]  # first item in the first dimension, and all of its corresponding elemets
# Similar to arr_2d[0, :]

array([1, 2, 3])

In [38]:
a[1::2]

array([1, 3, 5, 7, 9])

In [39]:
a[:2]  # last index isn't included

array([0, 1])

#### View vs. Copy

In Python, slicing creates a view of an object, not a copy:

In [40]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [41]:
b[0] = 100
b

array([100,   2,   4,   6,   8])

In [42]:
a  # a is also changed!

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

Copying is done with `copy()`:

In [43]:
a_copy = a[::-1].copy()
a_copy

array([  9,   8,   7,   6,   5,   4,   3,   2,   1, 100])

In [44]:
a_copy[1] = 200
a_copy

array([  9, 200,   7,   6,   5,   4,   3,   2,   1, 100])

In [45]:
a  # unchanged

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

This behavior allows NumPy to save time and memory. It will usually go unnoticed during day-to-day use. Occasionally, however, it can result in ugly bugs which are hard to locate.

Let's look at a summary of 2D indexing:

![Numpy indexing](numpy_indexing.png)

### Aggregation

In [46]:
arr = np.random.random(1_000)
sum(arr)  # The native Python sum works on numpy arrays, but its use is discouraged in this context

512.7631727029587

`sum()` is a built-in Python function, capable of working on lists and other native Python data structures. NumPy has its own sum functions: You can either write `np.sum(arr)`, or use `arr.sum()`:

In [47]:
%timeit sum(arr)
%timeit np.sum(arr)
%timeit arr.sum()

211 µs ± 7.71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
4.39 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.87 µs ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Keep in mind that the built-in `sum()` and numpy's `np.sum()` aren't identical. `np.sum()` by default calculates the sum of _all axes_, returning a single number for multi-dimensional arrays.

In MATLAB, this behavior is replicated with `sum(arr(:))`.

Likewise, `min()` and `max()` also have two "competing" versions:

In [48]:
%timeit min(arr)  # Native Python
%timeit np.min(arr)
%timeit arr.min()

125 µs ± 1.54 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
4.5 µs ± 61.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.02 µs ± 39.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Calculating the `min` of an array will, again, result in a single number:

In [49]:
arr2 = np.random.random((4, 4, 4))
arr2.min()

0.038580771529663105

If you wish to calculate it across an axis, use the `axis` keyword:

In [50]:
arr2.min(axis=0)

[[0.07637196 0.11851706 0.05473045 0.07816811]
 [0.09183216 0.06991563 0.28786821 0.36936303]
 [0.09021839 0.03858077 0.12515445 0.10292086]
 [0.41324246 0.18667301 0.1655201  0.46430161]]


*2D output (axis number 0 was "dropped")*

In [51]:
arr2.max(axis=(0, 1))

[0.95060274 0.95759997 0.91357163 0.91681919]


*1D output (the two first axes were summed over)*

Many other aggregation functions exist, including:
```
- np.var
- np.std
- np.argmin\argmax
- np.median
- ...
```
Most of them have an object-oriented version, i.e. `arr.var()`, and a procedural version, i.e. `np.var(arr)`.

### Fancy indexing

In NumPy, indexing an array with a different array is called "fancy" indexing. Perhaps confusingly, it creates a copy, not a view.

In [52]:
basic_array = np.arange(10)
basic_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
mask = (basic_array % 2 == 0)
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [54]:
b = basic_array[mask]  # also basic_array[basic_array % 2 == 0]
b

array([0, 2, 4, 6, 8])

MATLAB veterans shouldn't be surprised from this feature, but if you haven't seen it before make sure to have a firm grasp on it, as it's a very powerful technique.

In [55]:
b[:] = 999
print(f"basic array: {basic_array}")
print(f"b: {b}")

basic array: [0 1 2 3 4 5 6 7 8 9]
b: [999 999 999 999 999]


In [56]:
float_array = np.arange(start=0, stop=20, step=1.5)
float_array

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

In [57]:
float_array[[1, 2, 5, 5, 10]]  # copy, not a view. Meaning that the resulting array is a new
# instance of the original array, independent of it, in a different location in memory.

array([ 1.5,  3. ,  7.5,  7.5, 15. ])

Counting the amount of values that fit our condition can be done as follows:

In [58]:
basic_array = np.arange(10)
count_nonzero_result = np.count_nonzero(basic_array % 2 == 0)
sum_result = np.sum(basic_array % 2 == 0)

print(f"np.count_nonzero result: {count_nonzero_result}")
print(f"np.sum result: {sum_result}")
# In the latter case, True is 1 and False is 0

np.count_nonzero result: 5
np.sum result: 5


If we wish to add more conditions in to the mix, we can use the `&, |, ~, ^` operators (and, or, not, xor):

In [59]:
((basic_array % 2 == 1) & (basic_array != 3)).sum()  # uneven values that are different from 3

4

Note that `numpy` uses the `&, |, ~, ^` operators for element-by-element comparison, while the reserved `and` and `or` keywords evaluate the entire object:

In [60]:
np.sum((basic_array % 2 == 1) and (basic_array != 3))   # doesn't work, "and" isn't used this way here

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Sorting

Again we face a condition in which Python has its own `sort` functions, but numpy's `np.sort()` are much better suited for arrays. We can either sort in-place, or have a new object back:

In [61]:
# Return a new object:
arr = np.array([ 3, 4, 1, 8, 10, 2, 4])
print(np.sort(arr))

# Sort in-place:
arr.sort()
print(arr)

[ 1  2  3  4  4  8 10]
[ 1  2  3  4  4  8 10]


The default implementation is a _quicksort_ but other sorting algorithms can be found as well.

In [62]:
# np.argsort will return the indices of the sorted array:
arr = np.array([ 3, 4, 1, 8, 10, 2, 4])
print("Sorted indices: {}".format(np.argsort(arr)))

# Usage is as follows:
arr[np.argsort(arr)]

Sorted indices: [2 5 0 1 6 3 4]


array([ 1,  2,  3,  4,  4,  8, 10])

### Concatenation

Concatenation (and splitting) in `numpy` works as follows:

In [63]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])  # concatenates along the first axis

array([1, 2, 3, 3, 2, 1])

In [64]:
# Concatenate more than two arrays
z = [99, 99, 99]
np.concatenate([x, y, z])  # notice how the function argument is an iterable!

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [65]:
# 2D - along the last axis
twod_1 = np.array([[0, 1, 2],
                   [3, 4, 5]])
twod_2 = np.array([[6, 7, 8],
                   [9, 10, 11]])
np.concatenate((twod_1, twod_2), axis=-1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

`np.vstack()` and `np.hstack()` are also an option:

In [66]:
sim1 = np.array([0, 1, 2])
sim2 = np.array([[30, 40, 50],
                 [60, 70, 80]])
np.vstack((sim1, sim2))

array([[ 0,  1,  2],
       [30, 40, 50],
       [60, 70, 80]])

Splitting up arrays is also quite easy:

In [67]:
arr = np.arange(16).reshape((4, 4))  # see the tuple? Shapes of arrays always come in tuples
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
upper, lower = np.split(arr, [3])  # splits at the fourth line (of the first axis, by default)
print(upper)
print('---')
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---
[[12 13 14 15]]


### Exercise

#### a. Familiarization:

Create two random 3D arrays, at least 3x3x3 in size. The first should have random integers between 0 and 100, while the second should contain floating points numbers drawn from the normal distribution, with mean -1 and standard deviation of 2 

1. What are the default datatypes of integer and floating-point arrays in numpy?

2. Center the distribution of the first integer array around 0, with values between -1 and 1.

3. Caclulate their mean, standard deviation along the last axis, and sum along the second axis. Remember that arrays are, like everything in Python, objects.


#### b. _Iteration over an array:_ 

Find and return the indices of the two random arrays only where _both elements_ comply with -0.5 <= X <= 0.5. Do so in at least two distinct ways. These can include elementwise iteration, masked-arrays, and more.

Time the execution of the script using the IPython `%%timeit` magic if you have this tool near at hand.

#### c. _Broadcasting:_
1. Create a vector with length 100, filled with ones, and a 2D zero-filled array with its last dimension with size of 100. 
2. Using `np.tile`, add the vector and the array.
3. Did you have to use `np.tile` in this case? What feature of numpy allows this?
4. What happens to the non-tiled addition when the first dimension of the matrix is 100? Why?
5. Bonus: How can one add the matrix (in its new shape) and vector without np.tile()?

### Exercise solutions below...

In [ ]:
# a
# 1
low = 0
high = 100
arr1 = np.random.randint(low=low, high=high, size=(10, 10, 10))  # dtype is np.int32
arr2 = np.random.randn(10, 10, 10) * 2 - 1  # dtype is np.float64

# 2
middle = (high - low) / 2
arr1 = (arr1 - middle) / middle

# 3
print("arr1 (integers) stats:")
print(f"Mean: {arr1.mean()},\nSTD: {arr1.std(axis=-1)},\nSum: {arr1.sum(axis=1)}")
print("arr2 (normal distribution) stats:")
print(f"Mean: {arr2.mean()},\nSTD: {arr2.std(axis=-1)},\nSum: {arr2.sum(axis=1)}")

In [ ]:
%%timeit
# b
# 1 - elementwise
result = []
for idx, (item1, item2) in enumerate(zip(arr1.flat, arr2.flat)):
    if (-0.5 <= item1 <= 0.5) and (-0.5 <= item2 <= 0.5):
        result.append(idx)
result

In [ ]:
%%timeit
# b
# 2 - masked arrays createed by np.ravel(), np.where()
mask1 = ((-0.5 <= arr1.ravel()) & (arr1.ravel() <= 0.5))
mask2 = ((-0.5 <= arr2.ravel()) & (arr2.ravel() <= 0.5))
both_positive = np.logical_and(mask1, mask2)
result = np.where(both_positive)
result

As you can tell, the second solution is far more efficient than the first, and after a few read code blocks, the syntax presented there can be at least as clear as the one in the first solution.

In [ ]:
# c
# 1
vec = np.ones(100)
mat = np.zeros((10, 100))

# 2
tiled_vec = np.tile(vec, (10, 1))  # transpose is necessary
ans_tiled = mat + tiled_vec

# 3
ans_simple = mat + vec  # It's called array broadcasting

# 4
mat_transposed = mat.T
print(mat_transposed.shape)
# ans_trans = mat_transposed + vec  # fails because broadcasting is done over the last dimension

# 5 - np.newaxis is the answer - very perfomant
ans_newaxis = mat_transposed + vec[:, np.newaxis]